# Setup
title:               Saúl Becerra Torres
tagline:             'Productor de arte contemporáneo'
description:         'Portafolio de producción'
url:                 https://sbector.com/productor
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Saúl Becerra Torres
  url:               https://sbector.com/productor
  email:             saulbector@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
